(defun docker-slime-translation (app-name)
  (lexical-let ((docker-tramp-prefix (concat "/docker:" app-name ":"))
                (docker-prefix "/root/common-lisp/")
                (local-prefix (projectile-project-root)))
    (list (concat "^" app-name "$")
          `(lambda (emacs-filename)
             (if (string-prefix-p ,docker-tramp-prefix emacs-filename)
                 (string-remove-prefix ,docker-tramp-prefix emacs-filename)
               (concat ,docker-prefix (string-remove-prefix ,local-prefix emacs-filename))))
          `(lambda (lisp-filename)
             (if (string-prefix-p ,docker-prefix lisp-filename)
                 (concat ,local-prefix (string-remove-prefix ,docker-prefix lisp-filename))
               (concat ,docker-tramp-prefix lisp-filename))))))
